name: catchat-docker
services:
  main_app:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - DB_PATH=/app/data/chat.db
      - PORT=3030
    image: ghcr.io/awoo-co/catchat-docker:latest
    labels:
      icon: https://awoo-co.github.io/cdn/favicon.png
    ports:
      - target: 3030
        published: "3030"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/catchat-docker/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/catchat-docker/uploads
        target: /app/uploads
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://awoo-co.github.io/cdn/favicon.png
  index: /
  is_uncontrolled: false
  port_map: "3030"
  scheme: http
  store_app_id: catchat-docker
  title:
    custom: catchat-docker