name: catchat-frontend
services:
  frontend_app:
    cpu_shares: 10
    command: []
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PORT=3030
    image: catchat-frontend:latest
    labels:
      icon: https://awoo-co.github.io/cdn/favicon.png
    ports:
      - target: 3030
        published: "3030"
        protocol: tcp
    restart: unless-stopped
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: catchat-frontend
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://awoo-co.github.io/cdn/favicon.png
  index: /
  is_uncontrolled: false
  port_map: "3030"
  scheme: http
  store_app_id: catchat-frontend
  title:
    custom: catchat-frontend